name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: echo vars.TESTINPUT
        run: echo ${{ vars.TESTINPUT }}
        env:
          First_Name: Mona
      - name: Set TESTINPUT
        id: shasum
        run: |
          echo "TEST2=0.0.1" >> $vars
